# Generated by Django 5.1.1 on 2024-09-23 11:58

import pgvector.django.vector
from django.db import migrations


from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        VectorExtension(),
        migrations.AlterField(
            model_name="person",
            name="face_embedding",
            field=pgvector.django.vector.VectorField(dimensions=128),
        ),
    ]
