# Generated by Django 5.1.1 on 2024-09-23 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='organization',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='organization',
            name='username',
        ),
    ]
