# Generated by Django 5.1.1 on 2024-10-02 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='roles',
        ),
        migrations.RemoveField(
            model_name='person',
            name='role',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
