# Generated by Django 5.1.1 on 2024-10-12 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_person_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name': 'Organization', 'verbose_name_plural': 'Organizations'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name_plural': 'People'},
        ),
    ]
