# Generated by Django 5.1.1 on 2024-10-01 11:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_loginlog_organization_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonDetail',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('response_text', models.TextField(blank=True, null=True)),
                ('custom_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.customfield')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_detail', to='app.person')),
                ('selected_options', models.ManyToManyField(blank=True, to='app.option')),
            ],
            options={
                'unique_together': {('person', 'custom_field')},
            },
        ),
        migrations.DeleteModel(
            name='PersonDetails',
        ),
    ]
