# Generated by Django 5.1.1 on 2024-10-10 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_loginlog_organization'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
