# Generated by Django 5.1.1 on 2024-10-12 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_blacklist_notification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blacklist',
            options={'verbose_name_plural': 'Blacklisted People'},
        ),
    ]
